#ifndef __RESOURCE_H__
#define __RESOURCE_H__

#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

// Acceleration
#define IDA_MAIN 1

// Menu Id
#define IDM_MAIN 1000
#define IDM_LISTVIEW 1001

// Dialogs
#define IDD_MAIN 100

// Main Dlg
#define IDC_INPUT 100
#define IDC_CURRENT 101
#define IDC_LISTVIEW 102

// Main Menu
#define IDM_EXIT 1002
#define IDM_ALWAYSONTOP_CHK 1003
#define IDM_CHECKUPDATES_CHK 1004
#define IDM_WEBSITE 1005
#define IDM_DONATE 1006
#define IDM_CHECKUPDATES 1007
#define IDM_ABOUT 1008
#define IDM_COPY 1009
#define IDM_SELECT_ALL 1010

#define IDX_TIMEZONE 2000
#define IDX_LANGUAGE 3000

// Strings
#define IDS_UPDATE_NO 1
#define IDS_UPDATE_YES 2

#define IDS_FILE 3
#define IDS_EXIT 4
#define IDS_SETTINGS 5
#define IDS_ALWAYSONTOP_CHK 6
#define IDS_CHECKUPDATES_CHK 7
#define IDS_TIMEZONE 8
#define IDS_LANGUAGE 9
#define IDS_HELP 10
#define IDS_WEBSITE 11
#define IDS_DONATE 12
#define IDS_CHECKUPDATES 13
#define IDS_ABOUT 14

#define IDS_COPY 15

#define IDS_FMTNAME_RFC2822 16
#define IDS_FMTNAME_ISO8601 17
#define IDS_FMTNAME_UNIXTIME 18
#define IDS_FMTNAME_MACTIME 19
#define IDS_FMTNAME_MICROSOFTTIME 20
#define IDS_FMTNAME_FILETIME 21

#define IDS_FMTDESC_RFC2822 22
#define IDS_FMTDESC_ISO8601 23
#define IDS_FMTDESC_UNIXTIME 24
#define IDS_FMTDESC_MACTIME 25
#define IDS_FMTDESC_MICROSOFTTIME 26
#define IDS_FMTDESC_FILETIME 27

#define IDS_CURRENT 28

// Icons
#define IDI_MAIN 100

#endif // __RESOURCE_H__
