#ifndef __RESOURCE_H__
#define __RESOURCE_H__

#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

// Acceleration
#define IDA_MAIN 1

// Menu Id
#define IDM_MAIN 100
#define IDM_LISTVIEW 101

// Dialogs
#define IDD_MAIN 100

// Main Dlg
#define IDC_INPUT 102
#define IDC_CURRENT 103
#define IDC_LISTVIEW 104

// Main Menu
#define IDM_EXIT 105
#define IDM_ALWAYSONTOP_CHK 106
#define IDM_DARKMODE_CHK 107
#define IDM_CHECKUPDATES_CHK 108
#define IDM_CLASSICUI_CHK 109
#define IDM_WEBSITE 110
#define IDM_DONATE 111
#define IDM_CHECKUPDATES 112
#define IDM_ABOUT 113

#define IDM_COPY 114
#define IDM_COPY_VALUE 115
#define IDM_SELECT_ALL 116

#define IDX_TIMEZONE 1000
#define IDX_LANGUAGE 2000

// Strings
#define IDS_UPDATE_NO 1
#define IDS_UPDATE_YES 2
#define IDS_UPDATE_DOWNLOAD 3
#define IDS_UPDATE_DONE 4
#define IDS_UPDATE_ERROR 5
#define IDS_UPDATE_INIT 6
#define IDS_UPDATE_INSTALL 7

#define IDS_FILE 8
#define IDS_EXIT 9
#define IDS_SETTINGS 10
#define IDS_ALWAYSONTOP_CHK 11
#define IDS_CHECKUPDATES_CHK 12
#define IDS_TIMEZONE 13
#define IDS_LANGUAGE 14
#define IDS_HELP 15
#define IDS_WEBSITE 16
#define IDS_DONATE 17
#define IDS_CHECKUPDATES 18
#define IDS_ABOUT 19

#define IDS_COPY 20
#define IDS_COPY_VALUE 21

#define IDS_FMTNAME_RFC1123 22
#define IDS_FMTNAME_ISO8601 23
#define IDS_FMTNAME_UNIXTIME 24
#define IDS_FMTNAME_MACTIME 25
#define IDS_FMTNAME_MICROSOFTTIME 26
#define IDS_FMTNAME_FILETIME 27

#define IDS_FMTDESC_RFC1123 28
#define IDS_FMTDESC_ISO8601 29
#define IDS_FMTDESC_UNIXTIME 30
#define IDS_FMTDESC_MACTIME 31
#define IDS_FMTDESC_MICROSOFTTIME 32
#define IDS_FMTDESC_FILETIME 33

#define IDS_CURRENT 34
#define IDS_CLOSE 35
#define IDS_CLASSICUI_CHK 36
#define IDS_DARKMODE_CHK 37

// Icons
#define IDI_MAIN 100

#endif // __RESOURCE_H__
